enum StageType {
  CARD_DISTRIBUTION, MAFIA_COLLUSION, DON_CITY_INSPECTION, SHERIFS_CITY_INSPECTION,
  CITY_AWAKENING, DAY_SPEAKING, VOTING, AUTO_CRASH_SPEAKING, AUTO_CRASH_VOTING,
  AIR_CRASH_VOTING, DEAD_PLAYER_SPEAKING, CITY_SLEEPING, MAFIA_DOING_DIRTY_BUSINESS,
  DON_LOOKING_SHERIFF, SHERIFF_LOOKING_DON,
}

export default StageType;