export default {
  GameCard: {
    VOTE_ADDED: 'GameCard -> VOTE_ADDED',
    VOTE_REMOVED: 'GameCard -> VOTE_REMOVED',
    PLAYER_ROLE_CHANGED: 'GameCard -> PLAYER_ROLE_CHANGED',
    TIMER_STARTED: 'GameCard -> TIMER_STARTED',
    TIMER_PAUSED: 'GameCard -> TIMER_PAUSED',
    TIMER_SET: 'GameCard -> TIMER_SET',
    TIMER_INITIAL_SET: 'GameCard -> TIMER_INITIAL_SET',
    NEXT_REQUESTED: 'GameCard -> NEXT_REQUESTED',
    SUSPECT_TOGGLED: 'GameCard -> SUSPECT_TOGGLED',
    VOTE_TOGGLED: 'GameCard -> VOTE_TOGGLED',
    SHOOT_TOGGLED: 'GameCard -> SHOOT_TOGGLED',
    DON_CHECK_TOGGLED: 'GameCard -> DON_CHECK_TOGGLED',
    SHERIFF_CHECK_TOGGLED: 'GameCard -> SHERIFF_CHECK_TOGGLED',
  },
};